export { default as Fab } from './Fab.vue'
export { default as Alert } from './Alert.vue'
export { default as Theme } from './Theme.vue'
export { default as Locale } from './Locale.vue'
export { default as Focus } from '@/src/layouts/focus.vue'
