name: Build Android APK

on:
  push:
    tags:
      - 'v*'

jobs:
  build-android:
    runs-on: ubuntu-22.04
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4

      - name: Validate tag version set.
        run: |
          # Extract versions
          CARGO_TOML_VERSION=$(sed -n '/^version/ s/.*"\([^"]*\)".*/\1/p' src-tauri/Cargo.toml)
          GIT_TAG_VERSION=$(git describe --tags --abbrev=0 2>/dev/null | sed 's/^v//')
          TAURI_CONFIG_VERSION=$(sed -n '/"version"/ s/.*"\([^"]*\)"[^"]*,.*/\1/p' src-tauri/tauri.conf.json)
          FRONTEND_VERSION=$(sed -n 's/.*"version": *"\([0-9.]*\)".*/\1/p' package.json)

          # Print versions
          echo "Cargo.toml version: $CARGO_TOML_VERSION"
          echo "Git tag version:   $GIT_TAG_VERSION"
          echo "Tauri config version: $TAURI_CONFIG_VERSION"
          echo "Frontend version: $FRONTEND_VERSION"

          # Check if all versions match
          if [[ "$CARGO_TOML_VERSION" != "$TAURI_CONFIG_VERSION" || \
                "$FRONTEND_VERSION" != "$TAURI_CONFIG_VERSION" || \
                "$GIT_TAG_VERSION" != "$TAURI_CONFIG_VERSION" ]]; then
            echo "Error: Versions do not match!"
            exit 1
          fi

          echo "Success: All versions match."

      - name: Get build tool versions
        id: build_tool_versions
        shell: bash
        run: sed "s/ /=/" .build-tool-versions >> "$GITHUB_OUTPUT"

      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ steps.build_tool_versions.outputs.rust }}
          targets: aarch64-linux-android

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ steps.build_tool_versions.outputs.node }}
          cache: 'npm'

      - name: Cache the rust details
        uses: Swatinem/rust-cache@v2
        with:
          cache-targets: true
          cache-workspace-crates: true
          cache-bin: true
          workspaces: src-tauri
          save-if: true

      - name: Install dependencies
        run: |
          cargo install tauri-cli@2.9.5
          npm ci

      - name: Set up JDK
        uses: actions/setup-java@v5
        with:
          java-version: ${{ steps.build_tool_versions.outputs.jdk }}
          distribution: 'temurin'
          cache: gradle

      - name: Setup Android SDK
        uses: amyu/setup-android@v5
        with:
          sdk-version: ${{ steps.build_tool_versions.outputs.sdk }}
          ndk-version: ${{ steps.build_tool_versions.outputs.ndk }}

      - name: Setup Android signing
        run: |
          cd src-tauri/gen/android
          echo "keyAlias=${{ secrets.ANDROID_KEY_ALIAS }}" > keystore.properties
          echo "password=${{ secrets.ANDROID_KEY_PASSWORD }}" >> keystore.properties
          base64 -d <<< "${{ secrets.ANDROID_KEY_BASE64 }}" > $RUNNER_TEMP/keystore.jks
          echo "storeFile=$RUNNER_TEMP/keystore.jks" >> keystore.properties

      - name: Build Tauri Android
        run: |
          export NDK_HOME=$ANDROID_NDK
          export CARGOFLAGS="--locked"
          export RUSTFLAGS="--remap-path-prefix $PWD=. -C metadata=deadbeef"
          export SOURCE_DATE_EPOCH=1700000000
          cargo tauri android build --split-per-abi --target aarch64
          mkdir assets
          find  src-tauri/gen/android/app/build/outputs/apk/ -iname *-release.apk -exec cp {} assets \;
          find  src-tauri/gen/android/app/build/outputs/bundle/ -iname *-release.aab -exec cp {} assets \;

      - name: Create dist tar
        run: tar -czf dist.tar.gz dist/

      - name: Create target tar
        run: tar -cJf target.tar.gz src-tauri/target/

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            assets/*
            dist.tar.gz
            target.tar.gz
            LICENSE.md
            PRIVACY_POLICY.md
          generate_release_notes: true
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
