name: Deploy GitHub Pages

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - uses: actions/checkout@v4

      - name: Generate metadata JSON
        run: python3 gh/generate_data.py

      - name: Copy images
        run: cp -r fastlane/metadata/android/en-US/images gh/images

      - uses: actions/configure-pages@v5

      - uses: actions/upload-pages-artifact@v3
        with:
          path: gh

      - id: deployment
        uses: actions/deploy-pages@v4
